"""add status to threads

Revision ID: fe8fee1e1674
Revises: 8f1f3d2dad58
Create Date: 2026-08-26 18:04:03.629292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8fee1e1674'
down_revision: Union[str, Sequence[str], None] = '8f1f3d2dad58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('status', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'status')
    # ### end Alembic commands ###
