"""Regenerate the e2e fake backend's fixtures from the real Python code, so the
fake shows exactly what the app would:

    .venv/bin/python web/tests/e2e/make_fixtures.py

* launch-fixture.json   the launch plan templates (harness.launch)
* business-fixture.json a café's 100 days of synthetic sales and the real
                        How's business overview for them (harness.sales), on
                        a rainy Wednesday that looks slow, with Pro access
"""
import asyncio
import json
import random
import sys
from datetime import date, timedelta
from pathlib import Path

from sqlalchemy import create_engine
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

HERE = Path(__file__).parent
TODAY = date(2026, 10, 6)            # a Tuesday


@compiles(JSONB, "sqlite")
def _jsonb(_t, _c, **_k):
    return "JSON"


def launch() -> None:
    from harness.launch import kinds, plan
    out = {"_note": "Generated by make_fixtures.py from harness.launch (kinds.catalogue + plan.new_plan, size small, "
                    "renting yes).",
           "kinds": kinds.catalogue(),
           "plans": {k: plan.new_plan(kind=k, city="X", size="small", renting="yes") for k in kinds.KINDS}}
    (HERE / "launch-fixture.json").write_text(json.dumps(out, ensure_ascii=False, indent=1))


def rain_on(d: date) -> float:
    return 16.0 if d == TODAY + timedelta(days=1) else random.Random(d.toordinal()).choice([0, 0, 0, 0, 0, 9, 18])


def business() -> None:
    from harness.billing import entitlements
    from harness.db import brands as brands_db
    from harness.db import launch as launch_db
    from harness.db import sales as db
    from harness.db.models import Brand, Business, BusinessDay, BusinessEvent, LaunchPlan
    from harness.launch import plan as planner
    from harness.sales import service

    engine = create_engine("sqlite://", connect_args={"check_same_thread": False}, poolclass=StaticPool)
    for m in (Business, BusinessDay, BusinessEvent, Brand, LaunchPlan):
        m.__table__.create(engine)
    maker = sessionmaker(engine)
    for mod in (db, brands_db, launch_db):
        mod.SessionLocal = maker
    entitlements.billing_enabled = lambda: False
    service.local_today = lambda uid: TODAY

    async def geo(city):
        return (34.08, 74.8)

    async def wx(lat, lon, start, end, today):
        out, d = {}, start
        while d <= end:
            out[d] = (rain_on(d), 22.0)
            d += timedelta(days=1)
        return out

    service.weather.geocode, service.weather.days = geo, wx
    with maker() as s:
        s.add(Brand(id=200, user_id=1, name="Chinar Café", colors=[], hashtags=[]))
        s.commit()
    p = launch_db.create("1", planner.new_plan(kind="cafe", city="Srinagar", area="Rajbagh", size="small"))
    b = db.create("1", name="Chinar Café", kind="cafe", city="Srinagar", brand_id=200, launch_plan_id=p["id"])
    rnd = random.Random(7)
    wd = [0.85, 0.8, 0.9, 0.95, 1.1, 1.4, 1.3]
    days = []
    for i in range(100):
        d = TODAY - timedelta(days=100 - i)              # up to yesterday: today is logged in the demo
        s_ = 14500 * wd[d.weekday()] * (0.68 if rain_on(d) > 5 else 1) * (1 + 0.0015 * i) * rnd.gauss(1, 0.05)
        days.append({"day": d.isoformat(), "sales": round(s_), "bills": round(s_ / 315)})
    db.import_days(b["id"], days)
    ov = asyncio.run(service.overview("1", b["id"]))
    ov["business"].update(id=1)
    out = {"_note": "Generated by make_fixtures.py from harness.sales.service.overview (Pro access, a rainy Wednesday "
                    "tomorrow). The fake backend trims it for Free and Plus and updates the week when a day is logged.",
           "overview": ov}
    (HERE / "business-fixture.json").write_text(json.dumps(out, ensure_ascii=False, indent=1, default=str))
    f = ov["forecast"]
    print(f"tomorrow {f['value']} ({f['low']}-{f['high']}) {f['model']} acc {f['accuracy']} slow {ov['slow']} "
          f"reasons {[r['label'] for r in f['reasons']]} ideas {[i['title'] for i in ov['ideas']]}", file=sys.stderr)


if __name__ == "__main__":
    launch()
    business()
